uicc0 = {
  imsi = "<TEST_IMSI>";
  key = "<TEST_KEY>";
  opc = "<TEST_OPC>";
  pdu_sessions = ({
    dnn = "Internet";
    nssai_sst = 1;
  });
}

position0 = {
  x = 0.0;
  y = 0.0;
  z = 6377900.0;
}

@include "../channelmod_rfsimu_LEO_satellite.conf"
